backend:
  name: git-gateway
  branch: main # Branch que vai mexer no repositório

publish_mode: editorial_workflow # Para fazer um esquema de revisão de novas edições
media_folder: "public/uploads" # Onde os arquivos de mídia serão armazenados
public_folder: "/uploads" # Onde a parte de mídia vai poder ser acessada
display_url: https://faiscadesignjr.com.br/ # URL que será mostrado no UI do Netlify

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"

search: false
locale: 'pt'

collections:
  - name: "home"
    extension: "json"
    description: "Configurações da página principal"
    label: "Página Principal"
    folder: "content/homePage"
    slug: "homePage"
    create: false
    identifier_field: "banner.tittle"
    editor:
      preview: false
    fields:
      # BANNER
      - label: "Banner Principal"
        name: "banner"
        widget: "object"
        fields:
          - {label: "Descrição do Propósito", name: "purpose", widget: "string", default: "PROPORCIONAMOS SOLUÇÕES CRIATIVAS PARA PROJETOS EXCLUSIVOS"}
          - {label: "Logo Banner", name: "logo", widget: "image"}
          - {label: "Título", name: "tittle", widget: "string", default: "SOMOS A FAÍSCA!"}
          - {label: "Descrição da Empresa", name: "companyDesc", widget: "string", default: "UMA EMPRESA JÚNIOR DE DESIGN VISUAL E DE PRODUTO DA UFRGS"}

      # LEARN MORE
      - label: "Seção Learn More"
        name: "learnMore"
        widget: "object"
        fields:
          - {label: "O que fazemos", name: "desc", widget: "string", default: "nós fazemos design de um jeito que você nunca viu"}
          - {label: "Frase do Botão", name: "buttonPhrase", widget: "string", default: "Vem impulsionar sua marca"}
          - {label: "Rota do Botão", name: "buttonRoute", widget: "string", default: "/contato"}

      # NOSSOS SERVIÇOS
      - label: "Seção Serviços"
        name: "services"
        widget: "object"
        fields:
          - {label: "Título da Seção", name: "titleAllServices", widget: "string", default: "NOSSOS SERVIÇOS"}

      # CASES
      - label: "Seção Cases"
        name: "cases"
        widget: "object"
        fields:
          - {label: "Frase Cases", name: "phraseCases", widget: "string", default: "encontramos soluções ideais para cada tipo de desafio"}
          - {label: "Título Esquerda", name: "leftTitle", widget: "string", default: "CASES"}
          - {label: "Título Direita", name: "rightTitle", widget: "string", default: "SELECIONADOS"}
          - {label: "Texto Botão", name: "buttonPhrase", widget: "string", default: "Mais Projetos"}
          - {label: "Rota Botão", name: "buttonRoute", widget: "string", default: "/portfolio"}

      # DEPOIMENTOS
      - label: "Seção Depoimentos"
        name: "reviews"
        widget: "object"
        fields:
          - {label: "Título Depoimentos", name: "titleReviews", widget: "string", default: "O QUE NOSSOS CLIENTES TEM A DIZER"}

  - name: "servicos"
    label: "Serviços"
    description: "Lista de serviços oferecidos"
    folder: "content/servicos"
    create: true
    extension: "json"
    identifier_field: "titulo"
    sortable_fields: ["ordem"] 
    editor:
      preview: false
    fields:
      - {label: "Ordem", name: "ordem", widget: "number", value_type: "int", min: 1}
      - {label: "Título do Serviço", name: "titulo", widget: "string"}
    # - {label: "Descrição", name: "descricao", widget: "text"}
  
  - name: "cases homee"
    label: "Cases homee"
    description: "sera se foi?"
    folder: "content/cases"
    create: true
    extension: "json"
    identifier_field: "nomeProjeto"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" 
    editor:
      preview: false
    fields:
      - {label: "ID", name: "id", widget: "number"}
      - {label: "Nome do Projeto", name: "nomeProjeto", widget: "string"}
      - {label: "Imagem", name: "imagem", widget: "image"}
      - {label: "Link do Projeto", name: "projectLink", widget: "string"}

  - name: "depoimentos"
    label: "Depoimentos"
    description: "Reviews dos clientes"
    folder: "content/reviews"
    create: true
    extension: "json"
    identifier_field: "cliente"
    editor:
      preview: false
    fields:
      - {label: "Depoimento", name: "texto", widget: "text"}
      - {label: "Cliente", name: "cliente", widget: "string"}

  - name: "portfolio"
    extension: "json"
    description: "Coleção que vai conter as informação da pagina de portfólio do site da Faísca."
    label: "Porfólio"
    folder: "content/portfolio"
    slug: "portfolioPage"
    create: true
    editor:
      preview: false
    fields:
      - label: "Grandes projetos" 
        name: "portfolio_projetos" 
        widget: "list"
        min: 4
        max: 4
        fields: 
          - {label: "Nome do projeto", name: "projeto_destaque", widget: "relation", collection: "projetos", search_fields: ["nome_projeto"], value_field: "{{nome_projeto}}", display_fields: ["{{nome_projeto}}"]}
          - {label: "Título", name: "titulo_projeto", widget: "string"}
          - {label: "Subtítulo", name: "subtitulo_projeto", widget: "string"}
      
      - label: "Projetos para o carrossel"
        name: "portfolio_carrossel"
        collapsed: false
        widget: "list"
        min: 1
        max: 5
        fields:
          - {label: "Projeto", name: "projeto_carrossel", widget: "relation", collection: "projetos", search_fields: ["nome_projeto"], value_field: "{{nome_projeto}}", display_fields: ["{{nome_projeto}}"]}
  - name: "membros" # Nome usado da rota
    extension: "json"
    description: "Coleção que vai conter todos os membros da Faísca."
    label: "Membros" # Nome usado na label do Netlify 
    folder: "content/membros" # Local da pasta onde vão estar os arquivos
    create: true # Permite que usuários criem arquivos nesse local
    editor:
      preview: false
    slug: "{{fields.nome_membro}}" 
    fields: 
      - {label: "Nome", name: "nome_membro", widget: "string"}
      - {label: "Cargo", name: "cargo_membro", widget: "relation", collection: "cargos", search_fields: ["cargo"], value_field: "{{cargo}}"}
      - {label: "Foto", name: "foto_membro", widget: "image"}

  - name: "cargos" # Nome usado da rota
    extension: "json"
    description: "Coleção que vai conter todos os cargos da Faísca."
    label: "Cargos" # Nome usado na label do Netlify 
    folder: "content/cargos" # Local da pasta onde vão estar os arquivos
    create: true # Permite que usuários criem arquivos nesse local
    editor:
      preview: false
    slug: "{{fields.cargo}}" 
    fields: 
      - {label: "Cargo", name: "cargo", widget: "string"}

  - name: "projetos"
    extension: "json"
    description: "Coleção que vai conter os projetos da Faísca."
    label: "Projetos"
    folder: "content/projetos"
    create: true
    editor:
      preview: false
    slug: "{{fields.nome_projeto}}"
    fields:
      - {label: "Nome do projeto", name: "nome_projeto", widget: "string"}
      - {label: "Imagem de capa", name: "imagemCapa", widget: "image"}
      - {label: "Imagem sub-capa", name: "imagemSubCapa", widget: "image"}
      - {label: "Propósito do projeto", name: "textoPurpose", widget: "markdown"}
      - {label: "Serviço 1", name: "t1Services", widget: "string"}
      - {label: "Serviço 2", name: "t2Services", widget: "string"}
      - {label: "Serviço 3", name: "t3Services", widget: "string"}
      - {label: "Imagem serviço esquerda", name: "imageLeftSer", widget: "image"}
      - {label: "Imagem serviço direita", name: "imageRightSer", widget: "image"}
      - {label: "Imagem serviço inferior", name: "imageBottomSer", widget: "image"}
      - {label: "Valor 1", name: "t1Values", widget: "string"}
      - {label: "Valor 2", name: "t2Values", widget: "string"}
      - {label: "Valor 3", name: "t3Values", widget: "string"}
      - {label: "Imagem valor esquerda", name: "imageLeftVal", widget: "image"}
      - {label: "Imagem valor direita", name: "imageRightVal", widget: "image"}
      - {label: "Gerente do projeto", name: "gerente", widget: "relation", collection: "membros", search_fields: ["nome_membro"], value_field: "{{nome_membro}}", display_fields: ["{{nome_membro}} - {{cargo_membro}}"]}
      - label: "Projetistas envolvidos"
        name: 'projetistas'
        widget: "list"
        min: 1
        max: 2
        field: {label: "Projetista", name: "projetista", widget: "relation", collection: "membros", search_fields: ["nome_membro"], value_field: "{{nome_membro}}", display_fields: ["{{nome_membro}} - {{cargo_membro}}"]}
      - {label: "Texto do botão", name: "bottonText", widget: "string", default: "veja mais no nosso behance!"}
      - {label: "Link do Behance", name: "behanceLink", widget: "string"}
      - label: "Projetos relacionados (irão para o carrossel)"
        name: "relacionados_projetos"
        widget: "list"
        min: 1
        max: 5
        field: {label: "Projeto", name: "projeto_carrossel", widget: "relation", collection: "projetos", search_fields: ["nome_projeto"], value_field: "{{nome_projeto}}", display_fields: ["{{nome_projeto}}  {{imagemCapa}}"]}